version: "3.8"
services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    env_file: .env
    command: /app/gunicorn.sh
    expose:
      - 8000
    depends_on:
      - postgis
    volumes:
      - ./docker/production/django/data/:/data/

  postgis:
      build:
        context: .
        dockerfile: ./docker/production/postgis/Dockerfile
      volumes:
        - ./docker/production/postgis/data:/var/lib/postgresql/data
        - ./docker/production/postgis/backups:/backups
      env_file: .env

  swagger:
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - SWAGGER_JSON=/schema.yml
    volumes:
      - ./docker/production/swagger/data:/


  nginx:
    build:
      context: docker/production/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost"]
      interval: 45s
      timeout: 5s
      retries: 3
    ports:
      - "8081:80"
      - "4443:443"
    env_file: .env_http
    volumes:
      - ./docker/production/nginx/conf-templates:/etc/nginx/templates
      - ssl:/etc/letsencrypt
      - certbot:/var/www/certbot
      - ./log/:/var/log/nginx/
    depends_on:
      - django

  certbot:
    build:
      context: docker/production/certbot
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      nginx:
        condition: service_healthy
    env_file: .env_http
    volumes:
      - ssl:/etc/letsencrypt
      - certbot:/var/www/certbot
      - .log/certbot/:/var/log/letsencrypt/

volumes:
  ssl: {}
  certbot: {}